(function(g){var window=this;var hua=function(a,b){var c=[];g.Nf(b,function(a){var b;try{b=g.ij.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.p(b)?g.hj(b)&&c.push(a):c.push(a)},a);
return c},iua=function(a,b){var c=hua(a,b);
(0,g.F)(c,function(a){g.ij.prototype.remove.call(this,a)},a)},jua=function(a){return a.H?a.G+((0,g.E)()-a.B)/1E3:a.G},kua=function(){var a=g.jj;
iua(a,a.g.Dd(!0))},u9=function(a){g.Xw.call(this,"ScreenServiceProxy");
this.Oc=a;this.o=[];this.o.push(this.Oc.$_s("screenChange",(0,g.z)(this.DL,this)));this.o.push(this.Oc.$_s("onlineScreenChange",(0,g.z)(this.iI,this)))},v9=function(a){g.Tw("cloudview",a)},lua=function(a){v9("setApiReady_ "+a);
g.na("yt.mdx.remote.cloudview.apiReady_",a,void 0)},w9=function(){return g.u("yt.mdx.remote.cloudview.instance_")},mua=function(a){g.Ni[a]&&(a=g.Ni[a],(0,g.F)(a,function(a){g.Li[a]&&delete g.Li[a]}),a.length=0)},x9=function(){return g.u("yt.mdx.remote.connection_")},y9=function(a){g.na("yt.mdx.remote.connectData_",a,void 0)},nua=function(a){g.na("yt.mdx.remote.currentScreenId_",a,void 0)},z9=function(){return g.u("yt.mdx.remote.currentScreenId_")},B9=function(){if(!A9){var a=g.u("yt.mdx.remote.screenService_");
A9=a?new u9(a):null}return A9},C9=function(a){g.na("yt.mdx.remote.cloudview.initializing_",a,void 0)},D9=function(){return!!g.u("yt.mdx.remote.cloudview.apiReady_")},E9=function(a){v9("setCastInstalled_ "+a);
g.lj("yt-remote-cast-installed",a)},F9=function(a){g.Tw("cloudview",a)},oua=function(a,b){w9().init(a,b)},G9=function(){return!!g.mj("yt-remote-cast-installed")},pua=function(){v9("dispose");
var a=w9();a&&a.dispose();g.na("yt.mdx.remote.cloudview.instance_",null,void 0);lua(!1);g.Pi(H9);H9.length=0},qua=function(){var a=window.document.createElement("a");
g.Ae(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ta(a)},rua=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},sua=function(a){var b=g.Ji();
if(b)if(b.clear(a),a)mua(a);else for(var c in g.Ni)mua(c)},I9=function(){return g.u("yt.mdx.remote.channelParams_")||{}},K9=function(a){var b=x9();
y9(null);a||nua("");g.na("yt.mdx.remote.connection_",a,void 0);J9&&((0,g.F)(J9,function(b){b(a)}),J9.length=0);
b&&!a?g.Si("yt-remote-connection-change",!1):!b&&a&&g.Si("yt-remote-connection-change",!0)},tua=function(){return g.u("yt.mdx.remote.connectData_")},L9=function(){var a=z9();
if(!a)return null;var b=B9().Hd();return g.oi(b,a)},uua=function(a,b){E9(!0);
C9(!1);oua(a,function(a){a?(lua(!0),g.Ri("yt-remote-cast2-api-ready")):(F9("Failed to initialize cast API."),E9(!1),g.nj("yt-remote-cast-available"),g.nj("yt-remote-cast-receiver"),pua());b(a)})},vua=function(){return G9()?w9()?w9().getCastSession():(F9("getCastSelector: Cast is not initialized."),null):(F9("getCastSelector: Cast API is not installed!"),null)},wua=function(){if(g.uoa){var a=2,b=g.Iw(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Nw("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Kw,c)}},xua=function(){var a=qua(),b=window.document.getElementById(a),c=b&&g.hh(b,"loaded");
c||b&&!c||(b=rua(a,function(){g.hh(b,"loaded")||(g.gh(b,"loaded","true"),g.Ri(a),g.wi(g.ya(sua,a),0))}))},yua=function(a){return(0,g.Q)(a,function(a){return{key:a.id,
name:a.name}})},N9=function(a,b){z9();
L9()&&L9();nua(a.id);var c=new g.iz(M9,a,I9());c.connect(b,tua());c.subscribe("beforeDisconnect",function(a){g.Si("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){x9()&&(x9(),K9(null))});
K9(c)},O9=function(){var a=g.qj();
if(!a)return null;var b=B9().Hd();return g.oi(b,a)},P9=function(a){g.Tw("remote",a)},Q9=function(){var a=x9();
return!!a&&3!=a.getProxyState()},R9=function(){D9()?w9().stopSession():F9("stopSession called before API ready.");
var a=x9();a&&(a.disconnect(1),K9(null))},zua=function(){var a;
a=B9().Oc.$_gos();var b=L9();b&&x9()&&(g.ni(a,b)||a.push(b));return yua(a)},T9=function(a,b){g.dl.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.Yy;this.A=this.o=null;this.H=(0,g.z)(this.zG,this);this.F=(0,g.z)(this.ej,this);this.G=(0,g.z)(this.yG,this);this.J=(0,g.z)(this.JG,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Np,this),Aua(this))):c=3;0!=c&&(b?this.Np(c):g.wi((0,g.z)(function(){this.Np(c)},this),0));
var d=vua();d&&S9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},U9=function(a){return new g.cz(a.B.getPlayerContextData())},Bua=function(a,b,c,d,e){var f=U9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.gz(f,b,d);g.p(c)&&(g.ez(f,c),l.currentTime=c);g.p(k)&&(l.listId=k);V9(a,"setPlaylist",l);e||W9(a,f)},Aua=function(a){(0,g.F)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.ya(this.CI,a),this))},a)},Cua=function(a){(0,g.F)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},X9=function(a,b){50>a.C.uc()&&g.$y(a.C,b)},Y9=function(a,b,c){var d=U9(a);
g.ez(d,c);-1E3!=d.o&&(d.o=b);W9(a,d)},V9=function(a,b,c){a.B.sendMessage(b,c)},W9=function(a,b){Cua(a);
a.B.setPlayerContextData(g.hz(b));Aua(a)},S9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.ej(null));
a.A=b;a.A&&(Z9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.ej(a.A.media[0]))},Dua=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=U9(a);b.contentId!=d.videoId&&Z9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;g.ez(d,a.o.getEstimatedTime());W9(a,d)}else Z9("No cast media video. Ignoring state update.")},Z9=function(a){g.Tw("CP",a)},$9=function(a,b,c){return(0,g.z)(function(a){this.Tb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Tb("Retrying "+b+" using MDx browser channel."),V9(this,b,c))},a)},Eua=function(a){var b=!1;
w9()||(a=new g.xx(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.lj("yt-remote-cast-available",a);g.Si("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){v9("onReceiverSelected: "+a.friendlyName);
g.lj("yt-remote-cast-receiver",a);g.Si("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){v9("onReceiverResumed: "+a.friendlyName);
g.lj("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){v9("onSessionChange: "+g.ki(a));
a||g.nj("yt-remote-cast-receiver");g.Si("yt-remote-cast2-session-change",a)}),g.na("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
v9("cloudview.createSingleton_: "+b);return b},Fua=function(){var a=0<=g.jc.search(/\ (CrMo|Chrome|CriOS)\//);
return g.Fi||a},a$=function(a,b){D9()?w9().setConnectedScreenStatus(a,b):F9("setConnectedScreenStatus called before ready.")},Gua=function(){v9("clearCurrentReceiver");
g.nj("yt-remote-cast-receiver")},Hua=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){wua();a({command:"cast.sender.init"});return}}if(window.chrome)if(wua(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Gw();55<=b?a="55":50<=b&&(a="50");g.Nw("//www.gstatic.com/eureka/clank"+a+g.Lw,g.Kw)}else g.Ow(0);else g.Kw()},Iua=function(a){a?(g.lj("yt-remote-session-app",a.app),g.lj("yt-remote-session-name",a.name)):(g.nj("yt-remote-session-app"),g.nj("yt-remote-session-name"));
g.na("yt.mdx.remote.channelParams_",a,void 0)},Jua=function(){var a=I9();
if(g.Xb(a)){var a=g.pj(),b=g.mj("yt-remote-session-name")||"",c=g.mj("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.na("yt.mdx.remote.channelParams_",a,void 0)}},Kua=function(){var a=O9();
a?(P9("Resume connection to: "+g.ki(a)),N9(a,0)):(g.zj(),Gua(),P9("Skipping connecting because no session screen found."))},Lua=function(a){P9("remote.onCastSessionChange_: "+g.ki(a));
if(a){var b=L9();b&&b.id==a.id?a$(b.id,"YouTube TV"):(b&&R9(),N9(a,1))}else x9()&&R9()},Mua=function(){var a=zua(),b=L9();
b||(b=O9());return g.ab(a,function(a){return b&&g.hi(b,a.key)?!0:!1})},Nua=function(){var a=g.mj("yt-remote-cast-receiver");
return a?a.friendlyName:null},Oua=function(a,b,c,d){Fua()?Eua(b)&&(C9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?uua(a,c):(window.__onGCastApiAvailable=function(b,d){b?uua(a,c):(F9("Failed to load cast API: "+d),E9(!1),C9(!1),g.nj("yt-remote-cast-available"),g.nj("yt-remote-cast-receiver"),pua(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):xua():Hua())):v9("Cannot initialize because not running Chrome")},
Pua=function(a){this.B=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Zf(a)||"";b&&(this.B=":"+b);this.A=g.Yf(a)||"";a=g.jc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Sa(a,"10.0")&&(this.o=!1))},b$=function(a,b,c){g.H.call(this);
this.H=a;this.X=b;b.addEventListener("onVolumeChange",this.ll,this);b.addEventListener("onCaptionsTrackListChanged",this.tv,this);b.addEventListener("captionschanged",this.cv,this);b.addEventListener("captionssettingschanged",this.lp,this);b.addEventListener("videoplayerreset",this.hj,this);b.addEventListener("mdxautoplaycancel",this.$r,this);this.C=!1;this.g=c;c.isDisposed();c.subscribe("proxyStateChange",this.Gv,this);c.subscribe("remotePlayerChange",this.gj,this);c.subscribe("remoteQueueChange",
this.hj,this);c.subscribe("autoplayUpNext",this.av,this);c.subscribe("previousNextChange",this.Dv,this);c.subscribe("nowAutoplaying",this.wv,this);c.subscribe("autoplayDismissed",this.$u,this);this.suggestion=null;this.D=new g.Pl(64);this.o=new g.Od(this.Mw,500,this);g.J(this,this.o);this.A=new g.Od(this.Nw,1E3,this);g.J(this,this.A);this.B={};this.G=new g.Od(this.ax,1E3,this);g.J(this,this.G);this.F=new g.Aw(this.JN,1E3,this);g.J(this,this.F);this.J=g.w;this.lp();this.hj();this.gj()},c$=function(a,
b){var c=a.H,d=a.X.getVideoData().lengthSeconds;
c.H=b||0;c.g.Sa("progresssync",b,d)},Qua=function(a){c$(a,0);
a.o.stop();d$(a,new g.Pl(64))},g$=function(a,b){if(e$(a)&&!a.C){var c=null;
b&&(c={style:a.X.Gj()},g.dc(c,b));a.g.Gw(f$(a),c);a.B=U9(a.g).A}},h$=function(a,b){var c=a.X.De();
c?Bua(a.g,f$(a),b,c.g,c.listId.toString()):Bua(a.g,f$(a),b);d$(a,new g.Pl(1))},Rua=function(a,b){if(b){var c=a.X.Rc("captions","tracklist",{pu:1});
c&&c.length?(a.X.ge("captions","track",b),a.C=!1):(a.X.Cj("captions"),a.C=!0)}else a.X.ge("captions","track",{})},e$=function(a){return U9(a.g).videoId==f$(a)},f$=function(a){return a.X.getVideoData().videoId},d$=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.S(b,2);if(d!=g.S(a.D,2)){var e=a.X;(e=g.qm(e.app,e.playerType||1))&&g.aV(e,d)}a.D=b;Sua(a.H,c,b)}},i$=function(){var a=Mua();
!a&&G9()&&Nua()&&(a={key:"cast-selector-receiver",name:Nua()});return a},Tua=function(){var a=zua();
G9()&&g.mj("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Uua=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.jj&&kua();g.sj();M9||(M9=new Pua,g.Bj()&&(M9.g="/api/loungedev"));J9||(J9=g.u("yt.mdx.remote.deferredProxies_")||[],g.na("yt.mdx.remote.deferredProxies_",J9,void 0));Jua();var c=B9();if(!c){var d=new g.jx(M9);g.na("yt.mdx.remote.screenService_",d,void 0);c=B9();Oua(a,d,function(a){a?z9()&&a$(z9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.Si("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.u("yt.mdx.remote.initialized_")&&
(g.na("yt.mdx.remote.initialized_",!0,void 0),P9("Initializing: "+g.xf(b)),j$.push(g.Oi("yt-remote-cast2-availability-change",function(){g.Si("yt-remote-receiver-availability-change")})),j$.push(g.Oi("yt-remote-cast2-receiver-selected",function(){y9(null);
g.Si("yt-remote-auto-connect","cast-selector-receiver")})),j$.push(g.Oi("yt-remote-cast2-receiver-resumed",function(){g.Si("yt-remote-receiver-resumed","cast-selector-receiver")})),j$.push(g.Oi("yt-remote-cast2-session-change",Lua)),j$.push(g.Oi("yt-remote-connection-change",function(a){a?a$(z9(),"YouTube TV"):O9()||(a$(null,null),Gua())})),a=I9(),b.isAuto&&(a.id+="#dial"),g.Hh("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,P9(" -- with channel params: "+g.xf(a)),
Iua(a),c.start(),z9()||Kua())},k$=function(){G9()?w9()?D9()?(v9("Requesting cast selector."),w9().requestSession()):(v9("Wait for cast API to be ready to request the session."),H9.push(g.Oi("yt-remote-cast2-api-ready",k$))):F9("requestCastSelector: Cast is not initialized."):F9("requestCastSelector: Cast API is not installed!")},l$=function(a){g.Eu.call(this,a);
this.A={key:g.mi(),name:g.P("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.Pl(64);this.H=0},Sua=function(a,b,c){a.F=c;
a.g.Sa("presentingplayerstatechange",new g.vz(c,b))},m$=function(a,b,c){if(b.key!=a.B.key)if(b.key==a.A.key)R9();
else{a.B=b;var d;if(!c){c=a.g.De();d=a.g.getVideoData().videoId;var e;if(c){e=[];for(var f=0;f<c.B;f++)e[f]=c.Sb(f).videoId}else e=[a.g.getVideoData().videoId];d={videoIds:e,listId:a.g.ef(),videoId:d,index:Math.max(a.g.Jx(),0),currentTime:a.g.getCurrentTime()}}a=d;P9("Connecting to: "+g.xf(b));"cast-selector-receiver"==b.key?(y9(a||null),b=a||null,D9()?w9().setLaunchParams(b):F9("setLaunchParams called before ready.")):!a&&Q9()&&z9()==b.key?g.Si("yt-remote-connection-change",!0):(R9(),y9(a||null),
a=B9().Hd(),(b=g.oi(a,b.key))&&N9(b,1))}};
g.B(u9,g.Xw);g.h=u9.prototype;g.h.Hd=function(a){return this.Oc.$_gs(a)};
g.h.contains=function(a){return!!this.Oc.$_c(a)};
g.h.get=function(a){return this.Oc.$_g(a)};
g.h.start=function(){this.Oc.$_st()};
g.h.gm=function(a,b,c){this.Oc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Oc.$_r(a,b,c)};
g.h.Sl=function(a,b,c,d){this.Oc.$_un(a,b,c,d)};
g.h.R=function(){for(var a=0,b=this.o.length;a<b;++a)this.Oc.$_ubk(this.o[a]);this.o.length=0;this.Oc=null;u9.M.R.call(this)};
g.h.DL=function(){this.$("screenChange")};
g.h.iI=function(){this.$("onlineScreenChange")};
var A9=null,H9=[],J9=null,M9=null;g.B(T9,g.dl);g.h=T9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.w,$9(this,"play")):V9(this,"play"),Y9(this,1,g.fz(U9(this))),this.$("remotePlayerChange")):X9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.w,$9(this,"pause")):V9(this,"pause"),Y9(this,2,g.fz(U9(this))),this.$("remotePlayerChange")):X9(this,this.pause)};
g.h.yx=function(a){if(1==this.g){if(this.o){var b=U9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.ib()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.w,$9(this,"seekTo",{newTime:a}))}else V9(this,"seekTo",{newTime:a});Y9(this,3,a);this.$("remotePlayerChange")}else X9(this,g.ya(this.yx,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.w,$9(this,"stopVideo")):V9(this,"stopVideo");var a=U9(this);a.index=-1;a.videoId="";g.dz(a);W9(this,a);this.$("remotePlayerChange")}else X9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=U9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){Z9("set receiver volume: "+d)},this),(0,g.z)(function(){this.Tb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){Z9("set receiver muted: "+b)},this),(0,g.z)(function(){this.Tb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);V9(this,"setVolume",e)}c.muted=b;c.volume=a;W9(this,c)}else X9(this,g.ya(this.setVolume,a,b))};
g.h.Gw=function(a,b){if(1==this.g){var c=U9(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.xf(b.style),g.dc(d,c.A));V9(this,"setSubtitlesTrack",d);W9(this,c)}else X9(this,g.ya(this.Gw,a,b))};
g.h.Mp=function(a,b){if(1==this.g){V9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Fc.id});var c=U9(this);c.audioTrackId=b.Fc.id;W9(this,c)}else X9(this,g.ya(this.Mp,a,b))};
g.h.xx=function(a,b){if(1==this.g){if(a&&b){var c=U9(this);g.gz(c,a,b);W9(this,c)}V9(this,"previous")}else X9(this,g.ya(this.xx,a,b))};
g.h.wx=function(a,b){if(1==this.g){if(a&&b){var c=U9(this);g.gz(c,a,b);W9(this,c)}V9(this,"next")}else X9(this,g.ya(this.wx,a,b))};
g.h.Ns=function(){1==this.g?V9(this,"dismissAutoplay"):X9(this,this.Ns)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.$("proxyStateChange",a,this.g)}T9.M.dispose.call(this)};
g.h.R=function(){Cua(this);this.B=null;this.C.clear();S9(this,null);T9.M.R.call(this)};
g.h.Np=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.$("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.az(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.CI=function(a,b){this.$(a,b)};
g.h.zG=function(a){if(!a)this.ej(null),S9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=U9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Z9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W9(this,b)}};
g.h.ej=function(a){Z9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Dua(this),this.$("remotePlayerChange")};
g.h.yG=function(a){a?(Dua(this),this.$("remotePlayerChange")):this.ej(null)};
g.h.JG=function(){var a=vua();a&&S9(this,a)};
g.h.Tb=function(a){g.Tw("CP",a)};
var j$=[];g.h=Pua.prototype;g.h.vg=function(a,b,c){var d=this.g;if(g.p(c)?c:this.o)d="https://"+this.A+this.B+this.g;return g.gg(d+a,b||{})};
g.h.Lp=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Hb:g.ya(this.yL,c,!0),onError:g.ya(this.xL,d),$c:g.ya(this.zL,d)};b&&(c.Mb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Wi(a,c)};
g.h.yL=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.xL=function(a,b){a(Error("Request error: "+b.status))};
g.h.zL=function(a){a(Error("request timed out"))};
g.B(b$,g.H);g.h=b$.prototype;
g.h.R=function(){b$.M.R.call(this);this.o.stop();this.A.stop();this.J();this.X.removeEventListener("onVolumeChange",this.ll,this);this.X.removeEventListener("onCaptionsTrackListChanged",this.tv,this);this.X.removeEventListener("captionschanged",this.cv,this);this.X.removeEventListener("videoplayerreset",this.hj,this);this.X.removeEventListener("captionssettingschanged",this.lp,this);this.X.removeEventListener("mdxautoplaycancel",this.$r,this);this.g.Ka("proxyStateChange",this.Gv,this);this.g.Ka("remotePlayerChange",
this.gj,this);this.g.Ka("remoteQueueChange",this.hj,this);this.g.Ka("autoplayUpNext",this.av,this);this.g.Ka("previousNextChange",this.Dv,this);this.g.Ka("nowAutoplaying",this.wv,this);this.g.Ka("autoplayDismissed",this.$u,this);this.g=this.H=null};
g.h.zy=function(a,b){2==this.g.g||(e$(this)?this.JD.apply(this,arguments):this.FD.apply(this,arguments))};
g.h.cv=function(a){this.zy("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.lp=function(){var a=this.X.Rc("captions","track");g.Xb(a)||g$(this,a)};
g.h.FD=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":h$(this,this.X.getCurrentTime());break;case "control_seek":h$(this,c[0]);break;case "control_subtitles_set_track":g$(this,c[0]);break;case "control_set_audio_track":c=c[0],e$(this)&&this.g.Mp(f$(this),c)}};
g.h.JD=function(a,b){if(1081!=U9(this.g).o||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":U9(this.g).ib()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.mh(c[0],c[1]);break;case "control_subtitles_set_track":g$(this,c[0]);break;case "control_set_audio_track":c=c[0],e$(this)&&this.g.Mp(f$(this),c)}}};
g.h.ll=function(a){if(e$(this)){this.g.Ka("remotePlayerChange",this.gj,this);var b=Math.round(a.volume);a=!!a.muted;var c=U9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.gj,this)}};
g.h.tv=function(){g.Xb(this.B)||Rua(this,this.B);this.C=!1};
g.h.Gv=function(a,b){this.A.stop();2==b&&this.Nw()};
g.h.gj=function(){if(e$(this)){this.o.stop();var a=U9(this.g);switch(a.o){case 1081:d$(this,new g.Pl(8));break;case 1:this.Mw();d$(this,new g.Pl(8));break;case 1083:case 3:d$(this,new g.Pl(9));break;case 0:d$(this,new g.Pl(2));this.F.stop();c$(this,this.X.getVideoData().lengthSeconds);break;case 1082:d$(this,new g.Pl(4));break;case 2:d$(this,new g.Pl(4));c$(this,g.fz(a));break;case -1:d$(this,new g.Pl(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.P("YTP_MDX_PLAYER_ERROR")},d$(this,
new g.Pl(128,a))}var a=U9(this.g).A,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,Rua(this,a));a=U9(this.g);-1==a.volume||Math.round(this.X.getVolume())==a.volume&&this.X.Ld()==a.muted||this.G.isActive()||this.ax()}else Qua(this)};
g.h.Dv=function(){this.X.Sa("mdxpreviousnextchange")};
g.h.hj=function(){e$(this)||Qua(this)};
g.h.$r=function(){this.g.Ns()};
g.h.av=function(a){a&&(a=g.Wi("/watch_queue_ajax",{method:"GET",yc:{action_get_watch_queue_item:1,video_id:a},Hb:(0,g.z)(this.AJ,this)}))&&(this.J=(0,g.z)(a.abort,a))};
g.h.AJ=function(a,b){var c=new g.tt({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.X.Sa("mdxautoplayupnext",c)};
g.h.wv=function(a){(0,window.isNaN)(a)||this.X.Sa("mdxnowautoplaying",a)};
g.h.$u=function(){this.X.Sa("mdxautoplaycanceled")};
g.h.JN=function(a,b){-1==U9(this.g).o?h$(this,a):b&&this.g.yx(a)};
g.h.ax=function(){if(e$(this)){var a=U9(this.g);this.X.removeEventListener("onVolumeChange",this.ll,this);a.muted?this.X.mute():this.X.Ff();this.X.setVolume(a.volume);this.X.addEventListener("onVolumeChange",this.ll,this)}};
g.h.Mw=function(){this.o.stop();if(!this.g.isDisposed()){var a=U9(this.g);a.ib()&&d$(this,new g.Pl(8));c$(this,g.fz(a));this.o.start()}};
g.h.Nw=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.B(l$,g.Eu);g.h=l$.prototype;g.h.create=function(){Uua("embedded"==g.U(this.g).g);this.D.push(g.Oi("yt-remote-before-disconnect",this.vG,this));this.D.push(g.Oi("yt-remote-connection-change",this.KI,this));this.D.push(g.Oi("yt-remote-receiver-availability-change",this.Ev,this));this.D.push(g.Oi("yt-remote-auto-connect",this.II,this));this.D.push(g.Oi("yt-remote-receiver-resumed",this.HI,this));this.Ev()};
g.h.load=function(){this.g.an();l$.M.load.call(this);this.C=new b$(this,this.g,this.o);var a;a=(a=tua())?a.currentTime:0;var b=Q9()?new T9(x9(),void 0):null;0==a&&b&&(a=g.fz(U9(b)));0!=a&&(this.H=a||0,this.g.Sa("progresssync",a,void 0));Sua(this,this.F,this.F);g.C2(this.g.app,6)};
g.h.unload=function(){this.g.Sa("mdxautoplaycanceled");this.B=this.A;g.Ib(this.C,this.o);this.o=this.C=null;l$.M.unload.call(this);g.C2(this.g.app,5)};
g.h.R=function(){g.Pi(this.D);l$.M.R.call(this)};
g.h.Jj=function(a,b){this.loaded&&this.C.zy.apply(this.C,arguments)};
g.h.lD=function(){return this.loaded?this.C.suggestion:null};
g.h.my=function(){return this.o?U9(this.o).L:!1};
g.h.hasNext=function(){return this.o?U9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.kN=function(){var a=U9(this.o),b=this.g.getVideoData(),c=g.Gm(this.g),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.C+((0,g.E)()-a.B)/1E3:a.C;var l=1>=jua(a)-this.getCurrentTime(),m=a.J,n=jua(a),a=0<a.D?a.D+((0,g.E)()-a.B)/1E3:a.D;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.lN=function(){this.o&&this.o.wx()};
g.h.mN=function(){this.o&&this.o.xx()};
g.h.vG=function(a){1==a&&(this.J=this.o?U9(this.o):null)};
g.h.KI=function(){var a=Q9()?new T9(x9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Hb(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Jc(g.fz(a)));this.g.Sa("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.Ev=function(){this.G=[this.A].concat(Tua());var a=i$()||this.A;m$(this,a,!this.loaded);this.g.za("onMdxReceiversChange")};
g.h.II=function(){var a=i$();m$(this,a)};
g.h.HI=function(){this.B=i$()};
g.h.jN=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?k$():m$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&k$(),!0):!1}};
g.h.nN=function(){V9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.be=function(){return!1};
window._exportCheck==g.Ba&&g.na("ytmod.player.remote",l$,void 0);})(_yt_player);
