(function(){/*

SPF
(c) 2012-2016 Google Inc.
https://ajax.googleapis.com/ajax/libs/spf/2.4.0/LICENSE
*/
function l(a,b,c){var d=Array.prototype.slice.call(arguments,2);return function(){var c=d.slice();c.push.apply(c,arguments);return a.apply(b,c)}}function aa(a,b){if(a){var c=Array.prototype.slice.call(arguments,1);try{return a.apply(null,c)}catch(d){return d}}}function n(a,b){if(document.createEvent){var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,b);return document.dispatchEvent(c)}return!0}
var p=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};function ba(){};function ca(a){var b=document.body;b.dataset?b.dataset.spfName=a:b.setAttribute("data-"+"spfName".replace(/([A-Z])/g,"-$1").toLowerCase(),a)};function q(a,b){return r[a]=b}var r=window._spf_state||{};window._spf_state=r;function t(a,b){if(a.forEach)a.forEach(b,void 0);else for(var c=0,d=a.length;c<d;c++)c in a&&b.call(void 0,a[c],c,a)}function da(a,b){if(a.every)return a.every(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&!b.call(void 0,a[c],c,a))return!1;return!0}function ea(a,b){if(a.some)return a.some(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&b.call(void 0,a[c],c,a))return!0;return!1}
function fa(a,b){if(a.filter)return a.filter(b,void 0);var c=[];t(a,function(a,e,f){b.call(void 0,a,e,f)&&c.push(a)});return c}function ga(a,b){if(a.map)return a.map(b,void 0);var c=[];c.length=a.length;t(a,function(a,e,f){c[e]=b.call(void 0,a,e,f)});return c}function v(a){return"[object Array]"==Object.prototype.toString.call(a)?a:[a]};var ha={"animation-class":"spf-animate","animation-duration":425,"cache-lifetime":6E5,"cache-max":50,"cache-unified":!1,"link-class":"spf-link","nolink-class":"spf-nolink","navigate-limit":20,"navigate-lifetime":864E5,"reload-identifier":null,"request-timeout":0,"url-identifier":"?spf=__type__"},w={};"config"in r||q("config",w);w=r.config;function ia(a,b){b=b||document;return b.querySelectorAll?b.querySelectorAll(a):[]}function ja(a,b,c){for(;a;){if(b(a))return a;if(c&&a==c)break;a=a.parentNode}return null}function ka(a,b,c){b=b||document;var d=b.createElement("iframe");d.id=a||"";d.src='javascript:""';d.style.display="none";c&&(d.onload=l(c,null,d));b.body.appendChild(d);return d};function la(a,b,c,d){var e=d||{},f=!1,g=0,k,h=new XMLHttpRequest;h.open(a,b,!0);h.timing={};var m=h.abort;h.abort=function(){clearTimeout(k);h.onreadystatechange=null;m.call(h)};h.onreadystatechange=function(){var a=h.timing;if(2==h.readyState){a.responseStart=a.responseStart||p();if("json"==h.responseType)f=!1;else if(-1<(h.getResponseHeader("Transfer-Encoding")||"").toLowerCase().indexOf("chunked"))f=!0;else{var a=h.getResponseHeader("X-Firefox-Spdy"),c=window.chrome&&chrome.loadTimes&&chrome.loadTimes(),
c=c&&c.wasFetchedViaSpdy;f=!(!a&&!c)}e.M&&e.M(h)}else 3==h.readyState?f&&e.u&&(a=h.responseText.substring(g),g=h.responseText.length,e.u(h,a)):4==h.readyState&&(a.responseEnd=a.responseEnd||p(),window.performance&&window.performance.getEntriesByName&&(h.resourceTiming=window.performance.getEntriesByName(b).pop()),f&&e.u&&h.responseText.length>g&&(a=h.responseText.substring(g),g=h.responseText.length,e.u(h,a)),clearTimeout(k),e.L&&e.L(h))};"responseType"in h&&"json"==e.responseType&&(h.responseType=
"json");e.withCredentials&&(h.withCredentials=e.withCredentials);d="FormData"in window&&c instanceof FormData;a="POST"==a&&!d;if(e.headers)for(var C in e.headers)h.setRequestHeader(C,e.headers[C]),"content-type"==C.toLowerCase()&&(a=!1);a&&h.setRequestHeader("Content-Type","application/x-www-form-urlencoded");0<e.O&&(k=setTimeout(function(){h.abort();e.N&&e.N(h)},e.O));h.timing.fetchStart=p();h.send(c);return h};function x(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function ma(a){return"[object String]"==Object.prototype.toString.call(a)}var na=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")};function y(a,b){a=a.split(b);var c=1==a.length;return[a[0],c?"":b,c?"":a.slice(1).join(b)]};function oa(a){a.data&&ma(a.data)&&0==a.data.lastIndexOf("spf:",0)&&pa(a.data.substring(4))}function pa(a){var b=z[a];b&&(delete z[a],b())}function qa(a){window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent&&window.attachEvent("onmessage",a)}function ra(a){window.removeEventListener?window.removeEventListener("message",a,!1):window.detachEvent&&window.detachEvent("onmessage",a)}
var sa=function(){function a(){b=!1}if(!window.postMessage)return!1;var b=!0;qa(a);window.postMessage("","*");ra(a);return b}(),z={};"async-defers"in r||q("async-defers",z);z=r["async-defers"];sa&&("async-listener"in r&&ra(r["async-listener"]),qa(oa),q("async-listener",oa));function ta(a){var b=A();a in b&&delete b[a]}function ua(){var a=A(),b;for(b in a)va(a[b])||delete a[b];a=A();b=parseInt(w["cache-max"],10);b=isNaN(b)?Infinity:b;b=Object.keys(a).length-b;if(!(0>=b))for(var c=0;c<b;c++){var d=Infinity,e,f;for(f in a)a[f].count<d&&(e=f,d=a[f].count);delete a[e]}}function va(a){if(!(a&&"data"in a))return!1;var b=a.life,b=isNaN(b)?Infinity:b;a=a.time;return p()-a<b}function wa(a){var b=parseInt(r["cache-counter"],10)||0;b++;q("cache-counter",b);a.count=b}
function A(a){return!a&&"cache-storage"in r?r["cache-storage"]:q("cache-storage",a||{})};function xa(a){return a.classList?a.classList:a.className&&a.className.match(/\S+/g)||[]}function ya(a,b){if(b){if(a.classList)return a.classList.contains(b);a=xa(a);return ea(a,function(a){return a==b})}return!1}function B(a,b){b&&(a.classList?a.classList.add(b):ya(a,b)||(a.className+=" "+b))}function D(a,b){if(b)if(a.classList)a.classList.remove(b);else{var c=xa(a),c=fa(c,function(a){return a!=b});a.className=c.join(" ")}};function za(a,b,c){var d=null,e=window.history.state;if(e){var d={},f;for(f in e)d[f]=e[f]}if(b)for(f in d=d||{},b)d[f]=b[f];Aa(!0,a,d,c)}function Aa(a,b,c,d){if(b||c){b=b||window.location.href;c=c||{};var e=p();q("history-timestamp",e);c["spf-timestamp"]=e;if(a)Ba(c,b);else if(a=Ca().contentWindow.history.pushState,"function"==typeof a)a.call(window.history,c,"",b);else throw Error("history.pushState is not a function.");q("history-url",b);d&&(d=r["history-callback"])&&d(b,c)}}
function Da(a){var b=window.location.href;if(r["history-ignore-pop"])q("history-ignore-pop",!1);else if(a.state){a=a.state;var c=a["spf-timestamp"];b==r["history-url"]?(q("history-timestamp",c),Ba(a,b)):(a["spf-back"]=c<parseInt(r["history-timestamp"],10),a["spf-current"]=r["history-url"],q("history-timestamp",c),q("history-url",b),(c=r["history-callback"])&&c(b,a))}}
function Ba(a,b){var c=Ca().contentWindow.history.replaceState;if("function"==typeof c)c.call(window.history,a,"",b);else throw Error("history.replaceState is not a function");}function Ca(){var a=document.getElementById("history-iframe");a||(a=ka("history-iframe"));return a};function Ea(a,b){a&&b&&(a in E||(E[a]=[]),E[a].push(b))}function Ga(a,b){a in E&&b&&da(E[a],function(a,d,e){return a==b?(e[d]=null,!1):!0})}function Ha(a){a in E&&t(E[a],function(a,c,d){d[c]=null;a&&a()})}var E={};"ps-s"in r||q("ps-s",E);E=r["ps-s"];function F(a,b,c){var d=G[a];return a&&b?(d||(d=G[a]={items:[],o:0,m:0,A:1}),d.items.push({D:b,B:c||0})):d&&d.items.length||0}function H(a,b){var c=G[a];if(c){var d=!!c.o||!!c.m;0<c.A&&(b||!d)&&Ia(a,b)}}function I(a){(a=G[a])&&a.A--}function J(a,b){var c=G[a];c&&(c.A++,H(a,b))}function Ja(a){var b=G[a];b&&(Ka(b),delete G[a])}function Ia(a,b){var c=G[a];if(c&&(Ka(c),0<c.A&&c.items.length)){var d=c.items[0];d&&(a=l(function(a,b){b();a()},null,l(Ia,null,a,b)),b?(c.items.shift(),a(d.D)):La(c,d,a))}}
function La(a,b,c){b.B?(c=l(c,null,ba),a.m=setTimeout(c,b.B),b.B=0):(a.items.shift(),c=l(c,null,b.D),(b=(b=w["advanced-task-scheduler"])&&b.addTask)?a.o=b(c):a.m=setTimeout(c,0))}function Ka(a){if(a.o){var b=w["advanced-task-scheduler"];(b=b&&b.cancelTask)&&b(a.o);a.o=0}a.m&&(clearTimeout(a.m),a.m=0)}var G={};function K(a){var b=document.createElement("a");b.href=a;b.href=b.href;a={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,username:b.username,password:b.password};a.origin=a.protocol+"//"+a.host;a.pathname&&"/"==a.pathname[0]||(a.pathname="/"+a.pathname);return a}function L(a,b){a=K(a);return b?a.href:y(a.href,"#")[0]}
function Ma(a,b){var c=y(a,"#");a=c[0];t(b,function(b){a=a.replace(new RegExp("([?&])"+b+"(?:=[^&]*)?(?:(?=[&])|$)","g"),function(a,b){return"?"==b?b:""})});x(a,"?")&&(a=a.slice(0,-1));return a+c[1]+c[2]}function Na(a){var b=w["advanced-persistent-parameters"]||"",c=y(a,"#");a=c[0];var d=-1!=a.indexOf("?")?"&":"?";return a+(b?d+b:"")+c[1]+c[2]};function Oa(a,b,c,d){var e="js"==a;b=M(a,b);var f=c||"^"+b,g=N(a,f),k;c&&(k=O[N(a,c)])&&b!=k&&(n(e?"spfjsbeforeunload":"spfcssbeforeunload",{name:c,url:k}),e=k,delete O[N(a,c)],e&&delete P[N(a,e)],delete E[N(a,c)],Ea(g,l(Pa,null,a,c,k)));if((e=P[N(a,b)])&&f!=e){delete O[N(a,e)];delete P[N(a,b)];var h=N(a,e);h&&g&&h in E&&(E[g]=(E[g]||[]).concat(E[h]),delete E[h])}P[N(a,b)]=f;O[N(a,f)]=b;Ea(g,d);d=l(Qa,null,a);Q[N(a,b,void 0)]?(e&&f!=e&&(a=Ra(a,b))&&a.setAttribute("name",c||""),d()):(a=Sa(a,b,d,void 0,
void 0,k))&&c&&a.setAttribute("name",c)}function Ta(a,b){var c=O[N(a,b)];delete O[N(a,b)];c&&delete P[N(a,c)];delete E[N(a,b)];Pa(a,b,c)}function Pa(a,b,c){c&&(n("js"==a?"spfjsunload":"spfcssunload",{name:b,url:c}),Ua(a,c))}function Qa(a){var b=N(a,""),c;for(c in E)0==c.indexOf(b)&&da(c.substring(b.length).split("|"),l(Va,null,a))&&Ha(c)}
function Sa(a,b,c,d,e,f){function g(){Q[N(a,b,e)]&&(Q[N(a,b,e)]=2);k&&m&&m.parentNode&&h==document&&m.parentNode.removeChild(m);c&&setTimeout(c,0);return null}var k="js"==a;b=M(a,b);Q[N(a,b,e)]=1;var h=d||document,m=h.createElement(k?"script":"link");if(!b)return g();d=R(b);m.className=N(a,d);"onload"in m?m.onerror=m.onload=g:m.onreadystatechange=function(){/^c|loade/.test(m.readyState)&&g()};d=h.getElementsByTagName("head")[0]||h.body;k?(m.async=!0,m.src=b,d.insertBefore(m,d.firstChild)):(m.rel=
"stylesheet",m.href=b,(f=f?Ra(a,f,d):null)?d.insertBefore(m,f):d.appendChild(m));return m}function Ua(a,b){b=M(a,b);var c=Ra(a,b,void 0);c&&c.parentNode&&c.parentNode.removeChild(c);delete Q[N(a,b)]}function Ra(a,b,c){b=R(b);return ia("."+N(a,b),c)[0]}
function Wa(a){var b="js"==a,c=[];t(ia(b?"script[src]":'link[rel~="stylesheet"]'),function(d){var e=b?d.src:d.href,e=M(a,e);if(!Q[N(a,e,void 0)]){Q[N(a,e,void 0)]=2;var f=R(e);B(d,N(a,f));if(f=d.getAttribute("name"))P[N(a,e)]=f,O[N(a,f)]=e;c.push(d)}})}
function Xa(a,b,c){if(b&&(b=M(a,b),c||!Q[N(a,b,void 0)]))if(c&&"img"==a)Ya(b);else{var d=R(b),e=N(a,d),f=N(a,"prefetch"),d=document.getElementById(f);if(!d)d=ka(f,null,function(a){a.title=f;H(f,!0)});else if(!c&&d.contentWindow.document.getElementById(e))return;a=l(Za,null,d,a,b,e,f);d.title?a():F(f,a)}}
function Za(a,b,c,d,e){var f="js"==b,g="css"==b;a=a.contentWindow.document;var k=a.getElementById(d);k&&k.parentNode.removeChild(k);f?(k=a.createElement("object"),$a?a.createElement("script").src=c:k.data=c,k.id=d,a.body.appendChild(k)):g?(k=Sa(b,c,null,a,e),k.id=d):(k=a.createElement("img"),$a&&(c=c+"#"+p()),k.src=c,k.id=d,a.body.appendChild(k))}function Ya(a){var b=new Image;$a&&(a=a+"#"+p());b.src=a}
function ab(a,b,c){for(var d="js"==a,e=O[N(a,c)],f=b.replace(/\s/g,""),f=f||"",g=0,k=0,h=f.length;k<h;++k)g=31*g+f.charCodeAt(k),g%=4294967296;f="hash-"+g;O[N(a,c)]=f;!bb(a,f)&&(b=cb(a,b))&&(Q[N(a,f,void 0)]=2,b&&!d&&(d=R(f),b.className=N(a,d),b.setAttribute("name",c)),(e=e&&e[0])&&Ua(a,e))}
function cb(a,b){b=na(b);if(!b)return null;var c=document.getElementsByTagName("head")[0]||document.body;"js"==a?(a=document.createElement("script"),a.text=b,c.appendChild(a),c.removeChild(a)):(a=document.createElement("style"),c.appendChild(a),"styleSheet"in a?a.styleSheet.cssText=b:a.appendChild(document.createTextNode(b)));return a}
function M(a,b){var c="rsrc-p-"+a;if(b){var d=b.indexOf("//");if(0>d){if(0==b.lastIndexOf("hash-",0))return b;c=r[c]||"";if(ma(c))b=c+b;else for(var e in c)b=b.replace(e,c[e]);"img"!=a&&(b=0>b.indexOf("."+a)?b+"."+a:b);b=L(b)}else 0==d&&(b=L(b))}return b}function N(a,b,c){return a+"-"+b+(c?"-"+c:"")}function R(a){return a?String(a).replace(/[^\w]/g,""):""}function bb(a,b){a=Q[N(a,b,void 0)];return""==b||2==a}function Va(a,b){b=O[N(a,b)];return void 0!=b&&bb(a,b)}var Q={},P={},O={},$a=-1!=navigator.userAgent.indexOf(" Trident/");
"rsrc-s"in r||q("rsrc-s",Q);Q=r["rsrc-s"];"rsrc-n"in r||q("rsrc-n",P);P=r["rsrc-n"];"rsrc-u"in r||q("rsrc-u",O);O=r["rsrc-u"];function db(a){a=v(a);t(a,function(a){Xa("img",a,!0)})};function eb(a,b,c){Oa("js",a,b,c)}function fb(a){Ta("js",a)}function gb(a,b){Sa("js",a,b)}function hb(a){a=v(a);t(a,function(a){Xa("js",a)})}function ib(a,b,c){a=v(a);a=fa(a,function(a){return!!a});var d=[];t(a,function(a){void 0==O[N("js",a)]&&d.push(a)});var e=!d.length;if(b){var f=da(a,l(Va,null,"js"));e&&f?b():(a=N("js",a.sort().join("|")),Ea(a,b))}c&&!e&&c(d)}function jb(a,b){a=v(a);t(a,function(a){if(a){var b=S[a]||a,b=M("js",b),c=O[N("js",a)];c&&b!=c&&kb(a)}});ib(a,b,lb)}
function lb(a){t(a,function(a){function b(){eb(e,a)}var d=U[a],e=S[a]||a;d?jb(d,b):b()})}function kb(a){a=v(a);t(a,function(a){var b=[],d;for(d in U){var e=U[d],e=v(e);t(e,function(c){c==a&&b.push(d)})}t(b,function(a){kb(a)});fb(a)})}function mb(a,b){ab("js",a,b)}function nb(a){cb("js",a)}var U={};"js-d"in r||q("js-d",U);var U=r["js-d"],S={};"js-u"in r||q("js-u",S);S=r["js-u"];function ob(a,b,c){Oa("css",a,b,c)}function pb(a,b){Sa("css",a,b)}function qb(a){a=v(a);t(a,function(a){Xa("css",a)})};function rb(a,b,c){if(b){b=[];var d,e=0;c&&(a+="\r\n");var f=a.indexOf("[\r\n",e);for(-1<f&&(e=f+3);-1<(f=a.indexOf(",\r\n",e));)d=na(a.substring(e,f)),e=f+3,d&&b.push(JSON.parse(d));f=a.indexOf("]\r\n",e);-1<f&&(d=na(a.substring(e,f)),e=f+3,d&&b.push(JSON.parse(d)));d="";a.length>e&&(d=a.substring(e),c&&x(d,"\r\n")&&(d=d.substring(0,d.length-2)));b=sb(b);return{w:b,g:d}}a=JSON.parse(a);b=sb(v(a));return{w:b,g:""}}
function V(a,b,c,d){var e=c&&0==c.type.lastIndexOf("navigate",0),f=c&&c.reverse,g=c&&!!c.position,k=c&&c.j,h=b.name||"",m="process "+L(a),C=!w["experimental-process-async"],u;u=0;b.timing||(b.timing={});b.title&&(document.title=b.title);e&&b.url&&L(b.url)!=L(window.location.href)&&za(b.url+window.location.hash);b.head&&(u=l(function(a,b){a=W(a);tb(a);ub(a);I(m);vb(a,function(){b.spfProcessHead=p();J(m,C)})},null,b.head,b.timing),u=F(m,u));b.attr&&(u=l(function(a,b){for(var c in a){var d=document.getElementById(c);
if(d){var e=void 0,f=a[c];for(e in f){var g=f[e];"class"==e?d.className=g:"style"==e?d.style.cssText=g:(d.setAttribute(e,g),"value"==e&&(d[e]=g))}}}b.spfProcessAttr=p()},null,b.attr,b.timing),u=F(m,u));var T=b.body||{},uc=u,Fa;for(Fa in T)u=l(function(a,b){if(a=document.getElementById(a)){!e||g||k||(q("nav-scroll-position",null),q("nav-scroll-url",null),window.scroll(0,0),k=!0,c&&(c.j=!0));var d=W(b);ub(d);var u=function(){I(m);vb(d,function(){J(m,C)})};b=w["animation-class"];wb&&ya(a,b)?(a=new xb(a,
d.html,b,h,!!f),I(m),H(a.key,!0),F(a.key,l(yb,null,a),0),F(a.key,l(zb,null,a),17),F(a.key,l(Ab,null,a),a.T),F(a.key,l(function(){u();J(m,C)},null),0),H(a.key)):(b=w["experimental-html-handler"])?(I(m),b(d.html,a,function(){u();J(m,C)})):(a.innerHTML=d.html,u())}},null,Fa,T[Fa],b.timing),u=F(m,u);T=u-uc;b.foot?(u=l(function(a,b,c){c&&(b.spfProcessBody=p());a=W(a);ub(a);I(m);vb(a,function(){b.spfProcessFoot=p();J(m,C)})},null,b.foot,b.timing,T),u=F(m,u)):T&&(u=l(function(a){a.spfProcessBody=p()},null,
b.timing),u=F(m,u));d&&(u=F(m,l(d,null,a,b)));H(m,C)}function Bb(a,b,c,d){c="preprocess "+L(a);var e;b.head&&(e=l(function(a){a=W(a);tb(a);Cb(a);Db(a)},null,b.head),F(c,e));var f=b.body||{},g;for(g in f)f[g]&&(e=l(function(a,b){a=W(b);Cb(a);Db(a)},null,g,f[g]),F(c,e));b.foot&&(e=l(function(a){a=W(a);Cb(a);Db(a)},null,b.foot),F(c,e));d&&F(c,l(d,null,a,b));H(c)}
function yb(a){B(a.a,a.s);B(a.a,a.H);B(a.a,a.K);B(a.a,a.I);B(a.a,a.J);a.l=document.createElement("div");a.l.className=a.S;var b=a.a,c=a.l;if(c){for(var d;d=b.firstChild;)c.appendChild(d);b.appendChild(c)}a.f=document.createElement("div");a.f.className=a.R;a.f.innerHTML=a.P;a.reverse?(b=a.l,b.parentNode.insertBefore(a.f,b)):(b=a.l,b.parentNode.insertBefore(a.f,b.nextSibling))}function zb(a){D(a.a,a.I);D(a.a,a.J);B(a.a,a.F);B(a.a,a.G)}
function Ab(a){a.a.removeChild(a.l);var b=a.f,c,d=b.parentNode;if(d&&11!=d.nodeType)if(b.removeNode)b.removeNode(!1);else{for(;c=b.firstChild;)d.insertBefore(c,b);d.removeChild(b)}D(a.a,a.F);D(a.a,a.G);D(a.a,a.H);D(a.a,a.K);D(a.a,a.s)}function sb(a){t(v(a),function(a){if(a){a.head&&(a.head=W(a.head));if(a.body)for(var b in a.body)a.body[b]=W(a.body[b]);a.foot&&(a.foot=W(a.foot))}});return a}
function W(a){var b=new Eb;if(!a)return b;if(!ma(a))return a.scripts&&t(a.scripts,function(a){b.scripts.push({url:a.url||"",text:a.text||"",name:a.name||"",async:a.async||!1})}),a.styles&&t(a.styles,function(a){b.styles.push({url:a.url||"",text:a.text||"",name:a.name||""})}),a.links&&t(a.links,function(a){"spf-preconnect"==a.rel&&b.links.push({url:a.url||"",rel:a.rel||""})}),b.html=a.html||"",b;a=a.replace(Fb,function(a,d,e,f){if("script"==d){d=(d=e.match(Gb))?d[1]:"";var c=e.match(Hb),c=c?c[1]:"",
k=Ib.test(e);e=Jb.exec(e);return(e=!e||-1!=e[1].indexOf("/javascript")||-1!=e[1].indexOf("/x-javascript")||-1!=e[1].indexOf("/ecmascript"))?(b.scripts.push({url:c,text:f,name:d,async:k}),""):a}return"style"==d&&(d=(d=e.match(Gb))?d[1]:"",e=Jb.exec(e),e=!e||-1!=e[1].indexOf("text/css"))?(b.styles.push({url:"",text:f,name:d}),""):a});a=a.replace(Kb,function(a,d){var c=d.match(Lb),c=c?c[1]:"";return"stylesheet"==c?(c=(c=d.match(Gb))?c[1]:"",d=(d=d.match(Mb))?d[1]:"",b.styles.push({url:d,text:"",name:c}),
""):"spf-preconnect"==c?(d=(d=d.match(Mb))?d[1]:"",b.links.push({url:d,rel:c}),""):a});b.html=a;return b}function vb(a,b){if(0>=a.scripts.length)b&&b();else{var c=-1,d=function(){c++;if(c<a.scripts.length){var e=a.scripts[c],f=function(){};e.url?f=e.name?l(eb,null,e.url,e.name):l(gb,null,e.url):e.text&&(f=e.name?l(mb,null,e.text,e.name):l(nb,null,e.text));e.url&&!e.async?f(d):(f(),d())}else b&&b()};d()}}function Db(a){0>=a.scripts.length||(a=ga(a.scripts,function(a){return a.url}),hb(a))}
function ub(a){0>=a.styles.length||t(a.styles,function(a){a.url?a.name?ob(a.url,a.name):pb(a.url):a.text&&(a.name?ab("css",a.text,a.name):cb("css",a.text))})}function Cb(a){0>=a.styles.length||(a=ga(a.styles,function(a){return a.url}),qb(a))}function tb(a){0>=a.links.length||(a=ga(a.links,function(a){return"spf-preconnect"==a.rel?a.url:""}),db(a))}
function xb(a,b,c,d,e){var f=parseInt(w["animation-duration"],10);this.a=a;this.P=b;this.T=f;this.reverse=e;b=document.body;b=(b.dataset?b.dataset.spfName:b.getAttribute("data-"+"spfName".replace(/([A-Z])/g,"-$1").toLowerCase()))||"";f=parseInt(r.uid,10)||0;f++;this.key=a["spf-key"]||(a["spf-key"]=""+q("uid",f));this.H=b&&c+"-from-"+b;this.K=d&&c+"-to-"+d;this.l=null;this.S=c+"-old";this.f=null;this.R=c+"-new";this.s=c+(e?"-reverse":"-forward");this.I=c+"-start";this.J=this.s+"-start";this.F=c+"-end";
this.G=this.s+"-end"}function Eb(){this.html="";this.scripts=[];this.styles=[];this.links=[]}
var wb=function(){var a=document.createElement("div");return"transition"in a.style?!0:ea(["webkit","Moz","Ms","O","Khtml"],function(b){return b+"Transition"in a.style})}(),Kb=/\x3clink([\s\S]*?)\x3e/ig,Fb=/\x3c(script|style)([\s\S]*?)\x3e([\s\S]*?)\x3c\/\1\x3e/ig,Ib=/(?:\s|^)async(?:\s|=|$)/i,Mb=/(?:\s|^)href\s*=\s*["']?([^\s"']+)/i,Gb=/(?:\s|^)name\s*=\s*["']?([^\s"']+)/i,Lb=/(?:\s|^)rel\s*=\s*["']?([^\s"']+)/i,Hb=/(?:\s|^)src\s*=\s*["']?([^\s"']+)/i,Jb=/(?:\s|^)type\s*=\s*["']([^"']+)["']/i;function Nb(a,b){b=b||{};b.method=((b.method||"GET")+"").toUpperCase();b.type=b.type||"request";var c=a,d=w["url-identifier"]||"";if(d){var d=d.replace("__type__",b.type||""),e=y(c,"#"),f=y(e[0],"?"),c=f[0],g=f[1],f=f[2],k=e[1],e=e[2];if(0==d.lastIndexOf("?",0))g&&(d=d.replace("?","&")),f+=d;else{if(0==d.lastIndexOf(".",0))if(x(c,"/"))d="index"+d;else{var h=c.lastIndexOf(".");-1<h&&(c=c.substring(0,h))}else x(c,"/")&&0==d.lastIndexOf("/",0)&&(d=d.substring(1));c+=d}c=c+g+f+k+e}d=L(c);c={};c.spfUrl=
d;c.startTime=p();c.fetchStart=c.startTime;g=Ob(a,b.current,null,b.type,!1);g=Pb(g,b.current);c.spfPrefetched=!!g&&"prefetch"==g.type;c.spfCached=!!g;if(g){a=l(Qb,null,a,b,c,g.key,g.response);b=window._spf_state=window._spf_state||{};var m=parseInt(b.uid,10)||0;m++;b=b.uid=m;z[b]=a;sa?window.postMessage("spf:"+b,"*"):window.setTimeout(l(pa,null,b),0);return null}g={};if(f=w["request-headers"])for(m in f)k=f[m],g[m]=null==k?"":k;if(b.headers)for(m in b.headers)k=b.headers[m],g[m]=null==k?"":k;null!=
b.c&&(g["X-SPF-Referer"]=b.c);null!=b.current&&(g["X-SPF-Previous"]=b.current);if(m=w["advanced-header-identifier"])g["X-SPF-Request"]=m.replace("__type__",b.type),g.Accept="application/json";m=new Rb;f=l(Sb,null,a,b,c,m);a={headers:g,O:w["request-timeout"],M:l(Tb,null,a,m),u:l(Ub,null,a,b,c,m),L:f,N:f};b.withCredentials&&(a.withCredentials=b.withCredentials);w["advanced-response-type-json"]&&(a.responseType="json");return"POST"==b.method?la("POST",d,b.C,a):la("GET",d,null,a)}
function Qb(a,b,c,d,e){var f=!1;c.responseStart=c.responseEnd=p();b.type&&0==b.type.lastIndexOf("navigate",0)&&(c.navigationStart=c.startTime,w["cache-unified"]||(ta(d),f=!0));b.i&&"multipart"==e.type&&t(e.parts,function(d){d.timing||(d.timing={});d.timing.spfCached=!!c.spfCached;d.timing.spfPrefetched=!!c.spfPrefetched;b.i(a,d)});Vb(a,b,c,e,f)}function Tb(a,b,c){a=c.getResponseHeader("X-SPF-Response-Type")||"";b.f=-1!=a.toLowerCase().indexOf("multipart")}
function Ub(a,b,c,d,e,f,g){if(d.f){f=d.g+f;var k;try{k=rb(f,!0,g)}catch(h){e.abort();b.h&&b.h(a,h,e);return}b.i&&t(k.w,function(d){d.timing||(d.timing={});d.timing.spfCached=!!c.spfCached;d.timing.spfPrefetched=!!c.spfPrefetched;b.i(a,d)});d.a=d.a.concat(k.w);d.g=k.g}}
function Sb(a,b,c,d,e){if(e.timing)for(var f in e.timing)c[f]=e.timing[f];if(e.resourceTiming)if("load"==b.type)for(var g in e.resourceTiming)c[g]=e.resourceTiming[g];else if(window.performance&&window.performance.timing&&(f=window.performance.timing.navigationStart,f+e.resourceTiming.startTime>=c.startTime))for(var k in e.resourceTiming)g=e.resourceTiming[k],void 0!==g&&(x(k,"Start")||x(k,"End")||"startTime"==k)&&(c[k]=f+Math.round(g));"load"!=b.type&&(c.navigationStart=c.startTime);d.a.length&&
(d.g=na(d.g),d.g&&Ub(a,b,c,d,e,"",!0));var h;if("json"==e.responseType){if(!e.response){b.h&&b.h(a,Error("JSON response parsing failed"),e);return}h=sb(v(e.response))}else try{h=rb(e.responseText).w}catch(C){b.h&&b.h(a,C,e);return}if(b.i&&1<h.length)for(d=d.a.length;d<h.length;d++)e=h[d],e.timing||(e.timing={}),e.timing.spfCached=!!c.spfCached,e.timing.spfPrefetched=!!c.spfPrefetched,b.i(a,e);if(1<h.length){var m;t(h,function(a){a.cacheType&&(m=a.cacheType)});h={parts:h,type:"multipart"};m&&(h.cacheType=
m)}else h=1==h.length?h[0]:{};Vb(a,b,c,h,!0)}function Vb(a,b,c,d,e){if(e&&"POST"!=b.method&&(e=Ob(a,b.current,d.cacheType,b.type,!0))){d.cacheKey=e;var f={response:d,type:b.type||""},g=parseInt(w["cache-lifetime"],10),k=parseInt(w["cache-max"],10);0>=g||0>=k||(k=A(),f={data:f,life:g,time:p(),count:0},wa(f),k[e]=f,setTimeout(ua,1E3))}d.timing=c;b.v&&b.v(a,d)}
function Ob(a,b,c,d,e){a=L(a);var f;w["cache-unified"]?f=a:"navigate-back"==d||"navigate-forward"==d?f="history "+a:"navigate"==d?f=(e?"history ":"prefetch ")+a:"prefetch"==d&&(f=e?"prefetch "+a:"");b&&"url"==c?f+=" previous "+b:b&&"path"==c&&(f+=" previous "+K(b).pathname);return f||""}
function Pb(a,b){var c=[];b&&(c.push(a+" previous "+b),c.push(a+" previous "+K(b).pathname));c.push(a);var d=null;ea(c,function(a){var b;a:{b=A();if(a in b){b=b[a];if(va(b)){wa(b);b=b.data;break a}ta(a)}b=void 0}b&&(d={key:a,response:b.response,type:b.type});return!!b});return d}function Rb(){this.f=!1;this.g="";this.a=[]};function Wb(a){return ja(a,function(a){return ya(a,w["link-class"])})}function Xb(a){return ja(a,function(a){return ya(a,w["nolink-class"])})}function Yb(a,b){return ja(a,function(a){return a.href&&"img"!=a.tagName.toLowerCase()},b)}function Zb(a){if(a.metaKey||a.altKey||a.ctrlKey||a.shiftKey||0<a.button)return null;var b=Wb(a.target);return!b||w["nolink-class"]&&Xb(a.target)?null:(a=Yb(a.target,b))?a.href:null}function $b(a){return K(a).origin!=K(window.location.href).origin?!1:!0}
function ac(){if(!r["nav-init"])return!1;var a=parseInt(r["nav-counter"],10)||0;a++;var b=parseInt(w["navigate-limit"],10),b=isNaN(b)?Infinity:b;if(a>b)return!1;a=parseInt(r["nav-init-time"],10);a--;a=p()-a;b=parseInt(w["navigate-lifetime"],10);b=isNaN(b)?Infinity:b;return a>b?!1:!0}function bc(a,b){b=b||window.location.href;return-1!=a.indexOf("#")&&(a=L(a),b=L(b),a==b)?!1:!0}
function cc(a){if(!a.defaultPrevented){var b=Zb(a);b&&(b=Na(b),$b(b)&&ac()&&n("spfclick",{url:b,target:a.target})&&(dc(b,{},new ec),a.preventDefault()))}}function fc(a){var b=Zb(a);b&&setTimeout(function(){gc(b)},0)}function hc(){var a;a=r["nav-scroll-position"]||null;var b=r["nav-scroll-url"]||"";a=a&&b==window.location.href?a:null;ic();a&&window.scroll.apply(null,a)}
function jc(a,b){b=new ec({current:b&&b["spf-current"],history:!0,position:b&&b["spf-position"],c:b&&b["spf-referer"],reverse:!(!b||!b["spf-back"])});var c=w["reload-identifier"];c&&(a=Ma(a,[c]));$b(a)?ac()?n("spfhistory",{url:a,referer:b.c,previous:b.current})&&(b.position&&(q("nav-scroll-position",[window.pageXOffset,window.pageYOffset]),q("nav-scroll-url",window.location.href)),dc(a,{},b)):X(a,"1"):X(a,"9")}
function dc(a,b,c){kc();if(bc(a,c.current))if(lc(a,c.c,c.current,b)){q("nav-counter",(parseInt(r["nav-counter"],10)||0)+1);mc(a);var d=L(a),e="preprocess "+L(d),f;for(f in G)e!=f&&0==f.lastIndexOf("preprocess",0)&&Ja(f);d=nc()[d];q("nav-request",d);q("nav-promote",null);q("nav-promote-time",null);d&&4!=d.readyState?(d="preprocess "+L(a),e="promote "+L(a),q("nav-promote",a),q("nav-promote-time",p()),Ja(d),H(e,!0),c.history||oc(a,c.c,l(Y,null,b))):(d=l(Y,null,b),e=l(pc,null,b,c),f=l(qc,null,b,c),w["advanced-navigate-persist-timing"]||
rc(),c.type="navigate",c.history&&(c.type+=c.reverse?"-back":"-forward"),b=Nb(a,{method:b.method,headers:b.headers,i:e,h:d,v:f,C:b.postData,type:c.type,current:c.current,c:c.c}),q("nav-request",b),c.history||oc(a,c.c,d))}else X(a,"2");else c.history||oc(a,c.c,l(Y,null,b)),sc(a,c)}function sc(a,b){if(b.position)ic(),window.scroll.apply(null,b.position),b.j=!0;else if(a=y(a,"#"),a[2]){if(a=document.getElementById(a[2]))ic(),a.scrollIntoView(),b.j=!0}else b.j||(ic(),window.scroll(0,0),b.j=!0)}
function oc(a,b,c){try{za(null,{"spf-position":[window.pageXOffset,window.pageYOffset]}),L(a,!0)!=window.location.href&&Aa(!1,a,{"spf-referer":b},void 0)}catch(d){kc(),c(a,d)}}function Y(a,b,c,d){q("nav-request",null);tc(b,c,a,void 0,d)&&X(b,"10",c)}function pc(a,b,c,d){if(vc(c,d,a))if(d.reload)X(c,"5");else if(d.redirect)wc(a,d.redirect);else try{V(c,d,b,function(){xc(c,d,a)})}catch(e){Y(a,c,e)}else X(c,"3")}
function qc(a,b,c,d){q("nav-request",null);if(r["nav-promote"]==b.b){var e=d.timing||{};e.navigationStart=r["nav-promote-time"];e.spfPrefetched=!0}var f="multipart"==d.type;if(!f){if(!yc(c,d,a)){X(c,"4");return}if(d.reload){X(c,"5");return}if(d.redirect){wc(a,d.redirect);return}}try{V(c,f?{}:d,b,function(){var e=d.name||"";f&&t(d.parts,function(a){e=a.name||e});ca(e);sc(c,b);zc(c,d,a)})}catch(g){Y(a,c,g)}}function wc(a,b){try{b+=window.location.hash,za(b,null,!0)}catch(c){kc(),Y(a,b,c)}}
function kc(){var a=r["nav-request"];a&&(a.abort(),q("nav-request",null))}function Z(a,b){var c;a&&(c=Array.prototype.slice.call(arguments),c[0]=a,c=aa.apply(null,c));return!1!==c}
function X(a,b,c){c=c?c.message:"";kc();mc();var d=b;c&&(d+=" Message: "+c);n("spfreload",{url:a,reason:d});var e=window.location.href;w["experimental-remove-history"]&&e==a&&(q("history-ignore-pop",!0),window.history.back());setTimeout(function(){var c=w["reload-identifier"];if(c){var d={};d[c]=encodeURIComponent(b);var c=a,k=y(c,"#"),c=k[0],h=-1!=c.indexOf("?")?"&":"?",m;for(m in d)c+=h+m,d[m]&&(c+="="+d[m]),h="&";a=c+k[1]+k[2]}window.location.href=a;bc(a,e)||window.location.reload()},0)}
function Ac(a,b,c){c.b=c.b||a;if(lc(a,void 0,void 0,b,!0)){var d=l(Bc,null,!1,b,c),e=l(Cc,null,!1,b,c),f=l(Dc,null,!1,b,c);c.type="load";Nb(a,{method:b.method,headers:b.headers,i:e,h:d,v:f,C:b.postData,type:c.type,withCredentials:b.withCredentials})}}function gc(a,b){a=Na(a);Ec(a,b||{},new ec)}
function Ec(a,b,c){c.b=c.b||a;if(lc(a,void 0,void 0,b,!0)){var d=l(Bc,null,!0,b,c),e=l(Cc,null,!0,b,c),f=l(Dc,null,!0,b,c);c.type="prefetch";b=Nb(a,{method:b.method,headers:b.headers,i:e,h:d,v:f,C:b.postData,type:c.type,current:c.current});a=L(a);nc()[a]=b}}function Bc(a,b,c,d,e){a&&Fc(d);a&&r["nav-promote"]==c.b?Y(b,d,e):tc(d,e,b,!0)}
function Cc(a,b,c,d,e){if(vc(d,e,b,!0)){if(e.reload){if(!a)return;if(r["nav-promote"]==c.b){X(d,"5");return}}if(e.redirect)Gc(a,b,c,e.redirect);else{if(a){var f=l(pc,null,b,c,d,e),g="promote "+L(c.b);F(g,f);if(r["nav-promote"]==c.b){H(g,!0);return}}(a?Bb:V)(d,e,c,function(){xc(d,e,b,!0)})}}}
function Dc(a,b,c,d,e){var f="multipart"==e.type;if(!f){if(!yc(d,e,b,!0)){X(d,"4");return}if(e.reload){if(!a)return;if(r["nav-promote"]==c.b){X(d,"5");return}}if(e.redirect){Gc(a,b,c,e.redirect);return}}var g="promote "+L(c.b);if(a){Fc(d);if(r["nav-promote"]==c.b){F(g,l(qc,null,b,c,d,e));H(g,!0);return}Ja(g)}g=a?Bb:V;try{g(d,f?{}:e,c,function(){zc(d,e,b,!0)})}catch(k){Bc(a,b,c,d,k)}}
function Gc(a,b,c,d){a=a?Ec:Ac;var e={};t("onError onRequest onPartProcess onPartDone onProcess onDone".split(" "),function(a){e[a]=b[a]});a(d,e,c)}function tc(a,b,c,d,e){a={url:a,err:b,xhr:e};(c=Z((c||{}).onError,a))&&!d&&(c=n("spferror",a));return c}function lc(a,b,c,d,e){a={url:a,referer:b,previous:c};(d=Z((d||{}).onRequest,a))&&!e&&(d=n("spfrequest",a));return d}function vc(a,b,c,d){a={url:a,part:b};(c=Z((c||{}).onPartProcess,a))&&!d&&(c=n("spfpartprocess",a));return c}
function xc(a,b,c,d){a={url:a,part:b};Z((c||{}).onPartDone,a)&&!d&&n("spfpartdone",a)}function yc(a,b,c,d){a={url:a,response:b};(c=Z((c||{}).onProcess,a))&&!d&&(c=n("spfprocess",a));return c}function zc(a,b,c,d){a={url:a,response:b};Z((c||{}).onDone,a)&&!d&&n("spfdone",a)}function Fc(a){a=L(a);var b=nc(),c=b[a];c&&c.abort();delete b[a]}function mc(a){var b=nc();a=a&&L(a);for(var c in b)a!=c&&Fc(c)}
var rc,Hc=window.performance&&(window.performance.clearResourceTimings||window.performance.webkitClearResourceTimings||window.performance.mozClearResourceTimings||window.performance.msClearResourceTimings||window.performance.oClearResourceTimings);rc=Hc?l(Hc,window.performance):ba;function nc(){return"nav-prefetches"in r?r["nav-prefetches"]:q("nav-prefetches",{})}function ic(){q("nav-scroll-position",null);q("nav-scroll-url",null)}
function ec(a){a=a||{};this.current=a.history&&a.current?a.current:window.location.href;this.history=!!a.history;this.b=a.b||"";this.position=a.position||null;this.c=void 0!=a.c?a.c:window.location.href;this.reverse=!!a.reverse;this.j=!!a.j;this.type=a.type||""};function Ic(){Wa("js");Wa("css");"complete"==document.readyState&&(document.removeEventListener?document.removeEventListener("DOMContentLoaded",Ic,!1):document.detachEvent&&document.detachEvent("onreadystatechange",Ic))}document.addEventListener?document.addEventListener("DOMContentLoaded",Ic,!1):document.attachEvent&&document.attachEvent("onreadystatechange",Ic);Ic();
var Jc={init:function(a){var b=!("function"!=typeof window.history.pushState&&!Ca().contentWindow.history.pushState);a=a||{};for(var c in ha)w[c]=c in a?a[c]:ha[c];for(c in a)c in ha||(w[c]=a[c]);if(b){c=tc;if(!r["history-init"]&&window.addEventListener){a=window.location.href;window.addEventListener("popstate",Da,!1);q("history-init",!0);q("history-callback",jc);q("history-error-callback",c);q("history-listener",Da);q("history-url",a);q("history-timestamp",p());var d={"spf-referer":document.referrer};
try{za(a,d)}catch(e){c&&c(a,e)}}!r["nav-init"]&&document.addEventListener&&(q("nav-init",!0),q("nav-init-time",p()),q("nav-counter",0),document.addEventListener("click",cc,!1),q("nav-listener",cc),!w["experimental-prefetch-mousedown"]||"ontouchstart"in window||0<window.navigator.maxTouchPoints||0<window.navigator.msMaxTouchPoints||(document.addEventListener("mousedown",fc,!1),q("nav-mousedown-listener",fc)),document.addEventListener("scroll",hc,!1),q("nav-scroll-listener",hc))}return b},dispose:function(){"undefined"!=
typeof History&&History.prototype.pushState&&(kc(),r["nav-init"]&&(document.removeEventListener&&(document.removeEventListener("click",r["nav-listener"],!1),document.removeEventListener("mousedown",r["nav-mousedown-listener"],!1),document.removeEventListener("scroll",r["nav-scroll-listener"],!1)),q("nav-listener",null),q("nav-mousedown-listener",null),q("nav-scroll-listener",null),q("nav-scroll-position",null),q("nav-scroll-url",null),q("nav-init",!1),q("nav-init-time",null),q("nav-counter",null)),
r["history-init"]&&(window.removeEventListener&&window.removeEventListener("popstate",r["history-listener"],!1),q("history-init",!1),q("history-callback",null),q("history-error-callback",null),q("history-listener",null),q("history-url",null),q("history-timestamp",0)));for(var a in w)delete w[a]},navigate:function(a,b){a&&(a=Na(a),$b(a)?ac()?dc(a,b||{},new ec):X(a,"1"):X(a,"9"))},load:function(a,b){a=Na(a);Ac(a,b||{},new ec)},prefetch:gc,process:function(a,b){function c(a,c,d,e){a==c&&b&&b(e)}var d=
window.location.href;if("multipart"==a.type){a=a.parts;var e=a.length-1;t(a,function(a,b){V(d,a,null,l(c,null,b,e))})}else V(d,a,null,l(c,null,0,0))}},Kc={cache:{remove:ta,clear:function(){A({})}},script:{load:eb,get:gb,ready:ib,done:function(a){O[N("js",a)]="";Qa("js")},require:jb,declare:function(a,b){if(a){for(var c in a)U[c]=a[c];if(b)for(c in b)S[c]=b[c]}},path:function(a){q("rsrc-p-js",a)},unload:fb,ignore:function(a,b){a=v(a);a=N("js",a.sort().join("|"));Ga(a,b)},unrequire:kb,prefetch:hb},
style:{load:ob,get:pb,unload:function(a){Ta("css",a)},path:function(a){q("rsrc-p-css",a)},prefetch:qb}},global=this;global.spf=global.spf||{};var Lc=global.spf,Mc;for(Mc in Jc)Lc[Mc]=Jc[Mc];for(var Nc in Kc)for(var Oc in Kc[Nc])Lc[Nc]=Lc[Nc]||{},Lc[Nc][Oc]=Kc[Nc][Oc];n("spfready");}).call(this);
